"""Supplementary Queens/LIC neighborhood data — complete borough coverage.

Applies the same 4-dimension tier methodology.
Composite = (S*1.3 + B*1.0 + Q*1.2 + R*1.0) / 4.5
"""

REMAINING_QUEENS = [

    # ── Tier 1 ──────────────────────────────────────────────────────────────
    {
        "rank": 9, "name": "Ditmars Steinway", "tier": 1,
        "borough": "Queens",
        "centroid": (40.7778, -73.9060),
        "scores": {"safety": 5.0, "beauty": 4.0, "quiet": 4.5, "residential": 5.0},
        "composite": 4.64,
        "one_liner": "Northern Astoria residential core; extremely safe, quiet low-rise streets; strong community.",
        "source": {"base": "Ditmars Steinway"},
    },

    # ── Tier 2 ──────────────────────────────────────────────────────────────
    {
        "rank": 10, "name": "Bayside", "tier": 2,
        "borough": "Queens",
        "centroid": (40.7582, -73.7679),
        "scores": {"safety": 5.0, "beauty": 3.5, "quiet": 4.5, "residential": 4.5},
        "composite": 4.42,
        "one_liner": "Very safe, quiet northeast Queens waterfront community; pleasant but no brownstone character.",
        "source": {"base": "Bayside"},
    },
    {
        "rank": 11, "name": "Belle Harbor", "tier": 2,
        "borough": "Queens",
        "centroid": (40.5761, -73.8518),
        "scores": {"safety": 4.5, "beauty": 3.5, "quiet": 4.5, "residential": 4.5},
        "composite": 4.28,
        "one_liner": "Quiet beachfront bungalow community; very residential; flood risk and commute are trade-offs.",
        "source": {"base": "Belle Harbor"},
    },
    {
        "rank": 12, "name": "Douglaston", "tier": 2,
        "borough": "Queens",
        "centroid": (40.7631, -73.7422),
        "scores": {"safety": 5.0, "beauty": 3.5, "quiet": 5.0, "residential": 4.5},
        "composite": 4.56,
        "one_liner": "One of NYC's quietest residential peninsulas; colonials and Tudors; very far east on LIRR.",
        "source": {"base": "Douglaston"},
    },
    {
        "rank": 13, "name": "Forest Hills", "tier": 2,
        "borough": "Queens",
        "centroid": (40.7200, -73.8470),
        "scores": {"safety": 5.0, "beauty": 4.0, "quiet": 4.0, "residential": 4.5},
        "composite": 4.40,
        "one_liner": "Beautiful Tudor garden apartments; excellent E/F/M/R subway access; very residential.",
        "source": {"base": "Forest Hills"},
    },
    {
        "rank": 14, "name": "Hollis Hills", "tier": 2,
        "borough": "Queens",
        "centroid": (40.7335, -73.7533),
        "scores": {"safety": 5.0, "beauty": 3.5, "quiet": 5.0, "residential": 4.5},
        "composite": 4.56,
        "one_liner": "Very safe, very quiet eastern Queens residential area; suburban character; long commute.",
        "source": {"base": "Hollis Hills"},
    },
    {
        "rank": 15, "name": "Holliswood", "tier": 2,
        "borough": "Queens",
        "centroid": (40.7212, -73.7691),
        "scores": {"safety": 5.0, "beauty": 3.5, "quiet": 5.0, "residential": 4.5},
        "composite": 4.56,
        "one_liner": "Quiet, safe, tree-lined streets; detached homes; far from Manhattan.",
        "source": {"base": "Holliswood"},
    },
    {
        "rank": 16, "name": "Jamaica Estates", "tier": 2,
        "borough": "Queens",
        "centroid": (40.7197, -73.7889),
        "scores": {"safety": 5.0, "beauty": 3.5, "quiet": 5.0, "residential": 4.5},
        "composite": 4.56,
        "one_liner": "Upscale residential enclave; very safe and quiet; 45+ min Midtown commute.",
        "source": {"base": "Jamaica Estates"},
    },
    {
        "rank": 17, "name": "Kew Gardens", "tier": 2,
        "borough": "Queens",
        "centroid": (40.7085, -73.8291),
        "scores": {"safety": 4.5, "beauty": 3.5, "quiet": 4.0, "residential": 4.0},
        "composite": 4.03,
        "one_liner": "Compact, leafy, safe; good F-train access; pleasant prewar apartments and houses.",
        "source": {"base": "Kew Gardens"},
    },
    {
        "rank": 18, "name": "Little Neck", "tier": 2,
        "borough": "Queens",
        "centroid": (40.7655, -73.7304),
        "scores": {"safety": 5.0, "beauty": 3.5, "quiet": 5.0, "residential": 4.5},
        "composite": 4.56,
        "one_liner": "Easternmost Queens peninsula; extremely safe and quiet; very long commute to Manhattan.",
        "source": {"base": "Little Neck"},
    },
    {
        "rank": 19, "name": "Neponsit", "tier": 2,
        "borough": "Queens",
        "centroid": (40.5717, -73.8615),
        "scores": {"safety": 4.5, "beauty": 3.5, "quiet": 5.0, "residential": 4.0},
        "composite": 4.30,
        "one_liner": "Quiet, safe beachfront community with detached homes on the Rockaway Peninsula.",
        "source": {"base": "Neponsit"},
    },
    {
        "rank": 20, "name": "Whitestone", "tier": 2,
        "borough": "Queens",
        "centroid": (40.7867, -73.8110),
        "scores": {"safety": 5.0, "beauty": 3.5, "quiet": 4.5, "residential": 4.5},
        "composite": 4.42,
        "one_liner": "Safe, quiet north Queens waterfront; residential character; limited subway access.",
        "source": {"base": "Whitestone"},
    },

    # ── Tier 3 ──────────────────────────────────────────────────────────────
    {
        "rank": 21, "name": "Bay Terrace", "tier": 3,
        "borough": "Queens",
        "centroid": (40.7848, -73.7831),
        "scores": {"safety": 5.0, "beauty": 3.0, "quiet": 4.5, "residential": 4.5},
        "composite": 4.31,
        "one_liner": "Safe, quiet northeast Queens; modest mid-century architecture.",
        "source": {"base": "Bay Terrace"},
    },
    {
        "rank": 22, "name": "Bellerose", "tier": 3,
        "borough": "Queens",
        "centroid": (40.7360, -73.7263),
        "scores": {"safety": 5.0, "beauty": 3.0, "quiet": 4.5, "residential": 4.5},
        "composite": 4.31,
        "one_liner": "Very safe, quiet; far eastern Queens border with Nassau County.",
        "source": {"base": "Bellerose"},
    },
    {
        "rank": 23, "name": "Breezy Point", "tier": 3,
        "borough": "Queens",
        "centroid": (40.5591, -73.9070),
        "scores": {"safety": 4.5, "beauty": 3.0, "quiet": 5.0, "residential": 4.0},
        "composite": 4.19,
        "one_liner": "Private gated beachfront cooperative; extremely quiet; no transit; flood zone.",
        "source": {"base": "Breezy Point"},
    },
    {
        "rank": 24, "name": "Briarwood", "tier": 3,
        "borough": "Queens",
        "centroid": (40.7108, -73.8142),
        "scores": {"safety": 4.0, "beauty": 3.0, "quiet": 3.5, "residential": 4.0},
        "composite": 3.64,
        "one_liner": "Quiet, residential central Queens; good E/F subway access; modest architecture.",
        "source": {"base": "Briarwood"},
    },
    {
        "rank": 25, "name": "Broad Channel", "tier": 3,
        "borough": "Queens",
        "centroid": (40.6157, -73.8146),
        "scores": {"safety": 4.0, "beauty": 3.0, "quiet": 4.5, "residential": 4.0},
        "composite": 3.91,
        "one_liner": "Tiny island community in Jamaica Bay; extremely quiet; very isolated.",
        "source": {"base": "Broad Channel"},
    },
    {
        "rank": 26, "name": "Corona", "tier": 3,
        "borough": "Queens",
        "centroid": (40.7431, -73.8593),
        "scores": {"safety": 3.5, "beauty": 3.0, "quiet": 3.5, "residential": 4.0},
        "composite": 3.50,
        "one_liner": "Dense, diverse central Queens; strong Latin American community; Flushing Meadows park nearby.",
        "source": {"base": "Corona"},
    },
    {
        "rank": 27, "name": "Floral Park", "tier": 3,
        "borough": "Queens",
        "centroid": (40.7424, -73.7078),
        "scores": {"safety": 5.0, "beauty": 3.0, "quiet": 5.0, "residential": 4.5},
        "composite": 4.44,
        "one_liner": "Extremely safe and quiet far-eastern Queens; detached homes; LIRR or very long commute.",
        "source": {"base": "Floral Park"},
    },
    {
        "rank": 28, "name": "Flushing", "tier": 3,
        "borough": "Queens",
        "centroid": (40.7524, -73.8140),
        "scores": {"safety": 4.0, "beauty": 3.0, "quiet": 3.0, "residential": 4.0},
        "composite": 3.51,
        "one_liner": "Vibrant Asian culinary capital; busy commercial hub; good 7-train access.",
        "source": {"base": "Flushing"},
    },
    {
        "rank": 29, "name": "Fresh Meadows", "tier": 3,
        "borough": "Queens",
        "centroid": (40.7389, -73.7847),
        "scores": {"safety": 4.5, "beauty": 3.0, "quiet": 4.0, "residential": 4.5},
        "composite": 4.03,
        "one_liner": "Safe, residential mid-Queens; mid-century planned community; limited transit.",
        "source": {"base": "Fresh Meadows"},
    },
    {
        "rank": 30, "name": "Glen Oaks", "tier": 3,
        "borough": "Queens",
        "centroid": (40.7529, -73.7158),
        "scores": {"safety": 5.0, "beauty": 3.0, "quiet": 5.0, "residential": 4.5},
        "composite": 4.44,
        "one_liner": "Very safe and quiet planned community at Queens/Nassau border; bus-only transit.",
        "source": {"base": "Glen Oaks"},
    },
    {
        "rank": 31, "name": "Glendale", "tier": 3,
        "borough": "Queens",
        "centroid": (40.7035, -73.8791),
        "scores": {"safety": 4.5, "beauty": 3.0, "quiet": 4.5, "residential": 5.0},
        "composite": 4.28,
        "one_liner": "Safe, quiet, strongly residential; German and Italian heritage; modest architecture.",
        "source": {"base": "Glendale"},
    },
    {
        "rank": 32, "name": "Howard Beach", "tier": 3,
        "borough": "Queens",
        "centroid": (40.6578, -73.8447),
        "scores": {"safety": 4.0, "beauty": 3.0, "quiet": 4.0, "residential": 4.5},
        "composite": 3.89,
        "one_liner": "Safe, quiet waterfront community; Italian-American; A train access; modest architecture.",
        "source": {"base": "Howard Beach"},
    },
    {
        "rank": 33, "name": "Kew Gardens Hills", "tier": 3,
        "borough": "Queens",
        "centroid": (40.7247, -73.8198),
        "scores": {"safety": 4.5, "beauty": 3.0, "quiet": 4.0, "residential": 4.0},
        "composite": 3.92,
        "one_liner": "Safe, residential; strong Orthodox Jewish community; modest mid-century buildings.",
        "source": {"base": "Kew Gardens Hills"},
    },
    {
        "rank": 34, "name": "Maspeth", "tier": 3,
        "borough": "Queens",
        "centroid": (40.7262, -73.9056),
        "scores": {"safety": 4.0, "beauty": 3.0, "quiet": 3.5, "residential": 3.5},
        "composite": 3.53,
        "one_liner": "Working-class residential; industrial adjacency limits character; decent safety.",
        "source": {"base": "Maspeth"},
    },
    {
        "rank": 35, "name": "Middle Village", "tier": 3,
        "borough": "Queens",
        "centroid": (40.7156, -73.8792),
        "scores": {"safety": 5.0, "beauty": 3.0, "quiet": 4.5, "residential": 5.0},
        "composite": 4.42,
        "one_liner": "Very safe, very residential central Queens; strong community; limited direct subway.",
        "source": {"base": "Middle Village"},
    },
    {
        "rank": 36, "name": "Queens Village", "tier": 3,
        "borough": "Queens",
        "centroid": (40.7167, -73.7425),
        "scores": {"safety": 4.0, "beauty": 3.0, "quiet": 3.5, "residential": 4.0},
        "composite": 3.64,
        "one_liner": "Residential eastern Queens; safe, modest architecture; LIRR access.",
        "source": {"base": "Queens Village"},
    },
    {
        "rank": 37, "name": "Rego Park", "tier": 3,
        "borough": "Queens",
        "centroid": (40.7263, -73.8615),
        "scores": {"safety": 4.5, "beauty": 3.5, "quiet": 3.5, "residential": 4.0},
        "composite": 3.90,
        "one_liner": "Safe, good E/F/M/R subway access; mix of prewar and modern; busy commercial strip.",
        "source": {"base": "Rego Park"},
    },
    {
        "rank": 38, "name": "Richmond Hill", "tier": 3,
        "borough": "Queens",
        "centroid": (40.6919, -73.8262),
        "scores": {"safety": 3.5, "beauty": 3.0, "quiet": 3.5, "residential": 4.0},
        "composite": 3.50,
        "one_liner": "Diverse residential area; Indo-Caribbean community; modest Victorian row houses.",
        "source": {"base": "Richmond Hill"},
    },
    {
        "rank": 39, "name": "Ridgewood", "tier": 3,
        "borough": "Queens",
        "centroid": (40.7054, -73.9058),
        "scores": {"safety": 3.5, "beauty": 3.5, "quiet": 3.5, "residential": 4.0},
        "composite": 3.61,
        "one_liner": "Transitional Brooklyn/Queens border; improving; early-20th-century brick architecture.",
        "source": {"base": "Ridgewood"},
    },
    {
        "rank": 40, "name": "Rockaway Beach", "tier": 3,
        "borough": "Queens",
        "centroid": (40.5876, -73.8097),
        "scores": {"safety": 4.0, "beauty": 3.0, "quiet": 4.0, "residential": 3.0},
        "composite": 3.56,
        "one_liner": "Oceanfront boardwalk community; seasonal energy; far A-train commute.",
        "source": {"base": "Rockaway Beach"},
    },
    {
        "rank": 41, "name": "Rockaway Park", "tier": 3,
        "borough": "Queens",
        "centroid": (40.5813, -73.8319),
        "scores": {"safety": 4.5, "beauty": 3.5, "quiet": 4.0, "residential": 3.5},
        "composite": 3.92,
        "one_liner": "Quieter section of the Rockaway Peninsula; residential streets behind the beach.",
        "source": {"base": "Rockaway Park"},
    },
    {
        "rank": 42, "name": "Woodhaven", "tier": 3,
        "borough": "Queens",
        "centroid": (40.6915, -73.8574),
        "scores": {"safety": 4.0, "beauty": 3.0, "quiet": 3.5, "residential": 4.0},
        "composite": 3.64,
        "one_liner": "Residential central Queens; Forest Park adjacent; working-class character.",
        "source": {"base": "Woodhaven"},
    },

    # ── Tier 4 ──────────────────────────────────────────────────────────────
    {
        "rank": 43, "name": "Bayswater", "tier": 4,
        "borough": "Queens",
        "centroid": (40.6073, -73.7649),
        "scores": {"safety": 4.0, "beauty": 2.5, "quiet": 4.0, "residential": 4.0},
        "composite": 3.67,
        "one_liner": "Far Rockaways area; residential but remote, limited transit, modest architecture.",
        "source": {"base": "Bayswater"},
    },
    {
        "rank": 44, "name": "Cambria Heights", "tier": 4,
        "borough": "Queens",
        "centroid": (40.6932, -73.7368),
        "scores": {"safety": 3.5, "beauty": 2.5, "quiet": 4.0, "residential": 4.0},
        "composite": 3.52,
        "one_liner": "Far southeastern Queens; safe but long commute and limited amenities.",
        "source": {"base": "Cambria Heights"},
    },
    {
        "rank": 45, "name": "College Point", "tier": 4,
        "borough": "Queens",
        "centroid": (40.7818, -73.8410),
        "scores": {"safety": 4.0, "beauty": 2.5, "quiet": 4.0, "residential": 4.0},
        "composite": 3.67,
        "one_liner": "Industrial peninsula with residential pockets; no subway; modest character.",
        "source": {"base": "College Point"},
    },
    {
        "rank": 46, "name": "East Elmhurst", "tier": 4,
        "borough": "Queens",
        "centroid": (40.7626, -73.8805),
        "scores": {"safety": 3.5, "beauty": 3.0, "quiet": 3.0, "residential": 4.0},
        "composite": 3.37,
        "one_liner": "Near LaGuardia Airport; residential but affected by flight noise and variable safety.",
        "source": {"base": "East Elmhurst"},
    },
    {
        "rank": 47, "name": "Elmhurst", "tier": 4,
        "borough": "Queens",
        "centroid": (40.7374, -73.8789),
        "scores": {"safety": 3.5, "beauty": 3.0, "quiet": 3.0, "residential": 4.0},
        "composite": 3.37,
        "one_liner": "Dense, diverse; excellent transit; noisy commercial corridors; safety variable.",
        "source": {"base": "Elmhurst"},
    },
    {
        "rank": 48, "name": "Hollis", "tier": 4,
        "borough": "Queens",
        "centroid": (40.7122, -73.7670),
        "scores": {"safety": 3.0, "beauty": 2.5, "quiet": 3.5, "residential": 3.5},
        "composite": 3.13,
        "one_liner": "Southeast Queens residential; safety and architecture limit the score.",
        "source": {"base": "Hollis"},
    },
    {
        "rank": 49, "name": "Jamaica", "tier": 4,
        "borough": "Queens",
        "centroid": (40.6889, -73.7887),
        "scores": {"safety": 3.0, "beauty": 3.0, "quiet": 3.0, "residential": 3.5},
        "composite": 3.11,
        "one_liner": "Major southeastern Queens hub; busy transit center; safety and quiet below threshold.",
        "source": {"base": "Jamaica"},
    },
    {
        "rank": 50, "name": "Jamaica Hills", "tier": 4,
        "borough": "Queens",
        "centroid": (40.7134, -73.7994),
        "scores": {"safety": 3.5, "beauty": 2.5, "quiet": 3.5, "residential": 3.5},
        "composite": 3.28,
        "one_liner": "Near Jamaica hub; residential but below T3 threshold on beauty and composite.",
        "source": {"base": "Jamaica Hills"},
    },
    {
        "rank": 51, "name": "Laurelton", "tier": 4,
        "borough": "Queens",
        "centroid": (40.6766, -73.7429),
        "scores": {"safety": 3.5, "beauty": 2.5, "quiet": 3.5, "residential": 4.0},
        "composite": 3.39,
        "one_liner": "Far southeastern Queens; residential character but limited amenities and transit.",
        "source": {"base": "Laurelton"},
    },
    {
        "rank": 52, "name": "Ozone Park", "tier": 4,
        "borough": "Queens",
        "centroid": (40.6791, -73.8464),
        "scores": {"safety": 3.5, "beauty": 2.5, "quiet": 3.5, "residential": 4.0},
        "composite": 3.39,
        "one_liner": "Dense south Queens; working-class residential; modest architecture.",
        "source": {"base": "Ozone Park"},
    },
    {
        "rank": 53, "name": "Rosedale", "tier": 4,
        "borough": "Queens",
        "centroid": (40.6582, -73.7387),
        "scores": {"safety": 3.5, "beauty": 2.5, "quiet": 4.0, "residential": 4.0},
        "composite": 3.52,
        "one_liner": "Far southeastern Queens; safe but limited transit and modest architecture.",
        "source": {"base": "Rosedale"},
    },
    {
        "rank": 54, "name": "South Ozone Park", "tier": 4,
        "borough": "Queens",
        "centroid": (40.6713, -73.8132),
        "scores": {"safety": 3.5, "beauty": 2.5, "quiet": 3.5, "residential": 3.5},
        "composite": 3.28,
        "one_liner": "South Queens residential; JFK adjacency; limited character.",
        "source": {"base": "South Ozone Park"},
    },
    {
        "rank": 55, "name": "Springfield Gardens", "tier": 4,
        "borough": "Queens",
        "centroid": (40.6676, -73.7614),
        "scores": {"safety": 3.0, "beauty": 2.5, "quiet": 3.5, "residential": 3.5},
        "composite": 3.13,
        "one_liner": "Southeast Queens; safety and architecture below this profile's threshold.",
        "source": {"base": "Springfield Gardens"},
    },
    {
        "rank": 56, "name": "St. Albans", "tier": 4,
        "borough": "Queens",
        "centroid": (40.6968, -73.7633),
        "scores": {"safety": 3.0, "beauty": 2.5, "quiet": 3.5, "residential": 4.0},
        "composite": 3.24,
        "one_liner": "Historic jazz-era community; residential but safety and architecture below threshold.",
        "source": {"base": "St. Albans"},
    },

    # ── Tier 5 ──────────────────────────────────────────────────────────────
    {
        "rank": 57, "name": "Arverne", "tier": 5,
        "borough": "Queens",
        "centroid": (40.5934, -73.7955),
        "scores": {"safety": 2.5, "beauty": 2.5, "quiet": 3.5, "residential": 3.0},
        "composite": 2.90,
        "one_liner": "Rockaway Peninsula; safety below threshold; flood zone; very long commute.",
        "source": {"base": "Arverne"},
    },
    {
        "rank": 58, "name": "Edgemere", "tier": 5,
        "borough": "Queens",
        "centroid": (40.5972, -73.7777),
        "scores": {"safety": 2.5, "beauty": 2.0, "quiet": 3.5, "residential": 3.0},
        "composite": 2.73,
        "one_liner": "Rockaways; below safety threshold; flood zone; excluded from viable consideration.",
        "source": {"base": "Edgemere"},
    },
    {
        "rank": 59, "name": "Far Rockaway", "tier": 5,
        "borough": "Queens",
        "centroid": (40.6002, -73.7507),
        "scores": {"safety": 2.5, "beauty": 2.5, "quiet": 3.0, "residential": 3.0},
        "composite": 2.73,
        "one_liner": "Far eastern Rockaways; safety below threshold; outside viable search area.",
        "source": {"base": "Far Rockaway"},
    },
]

# Open space / non-residential areas in Queens (rendered in park color)
QUEENS_PARKS = [
    "Alley Pond Park",
    "Cunningham Park",
    "Flushing Meadows Corona Park",
    "Forest Park",
    "John F. Kennedy International Airport",
    "LaGuardia Airport",
]
