"""Supplementary Brooklyn neighborhood data — complete borough coverage.

Applies the same 4-dimension tier methodology as atlas_data.py and
brooklyn_lic_data.py.  These neighborhoods complete the Brooklyn map so no area
is left white.

Composite = (S*1.3 + B*1.0 + Q*1.2 + R*1.0) / 4.5
T1: composite ≥ 4.5, no dim < 4.0
T2: composite ≥ 4.0, ≤1 dim < 4.0, that dim ≥ 3.5
T3: composite ≥ 3.5, no dim < 3.0
T4: composite ≥ 3.0 or structural weakness
T5: composite < 3.0 OR S<3.0 OR Q<2.5 OR R<1.5
"""

REMAINING_BROOKLYN = [

    # ── Tier 2 ──────────────────────────────────────────────────────────────
    {
        "rank": 21, "name": "Dyker Heights", "tier": 2,
        "borough": "Brooklyn",
        "centroid": (40.6196, -74.0135),
        "scores": {"safety": 5.0, "beauty": 3.5, "quiet": 4.5, "residential": 5.0},
        "composite": 4.53,
        "one_liner": "Extremely safe and quiet Italian-American neighborhood; famous holiday decorations; far south Brooklyn.",
        "source": {"base": "Dyker Heights"},
    },
    {
        "rank": 22, "name": "Manhattan Beach", "tier": 2,
        "borough": "Brooklyn",
        "centroid": (40.5784, -73.9432),
        "scores": {"safety": 4.5, "beauty": 4.0, "quiet": 4.5, "residential": 4.5},
        "composite": 4.39,
        "one_liner": "Upscale beachfront enclave; very safe and quiet; no subway but exceptional residential feel.",
        "source": {"base": "Manhattan Beach"},
    },

    # ── Tier 3 ──────────────────────────────────────────────────────────────
    {
        "rank": 23, "name": "Bay Ridge", "tier": 3,
        "borough": "Brooklyn",
        "centroid": (40.6311, -74.0282),
        "scores": {"safety": 4.5, "beauty": 3.5, "quiet": 3.5, "residential": 4.5},
        "composite": 4.01,
        "one_liner": "Safe, residential, attractive; 3rd Ave nightlife corridor limits quiet score.",
        "source": {"base": "Bay Ridge"},
    },
    {
        "rank": 24, "name": "Bath Beach", "tier": 3,
        "borough": "Brooklyn",
        "centroid": (40.6036, -74.0066),
        "scores": {"safety": 4.5, "beauty": 3.0, "quiet": 4.5, "residential": 5.0},
        "composite": 4.28,
        "one_liner": "Quiet, safe, deeply residential Italian-American neighborhood; limited transit.",
        "source": {"base": "Bath Beach"},
    },
    {
        "rank": 25, "name": "Bensonhurst", "tier": 3,
        "borough": "Brooklyn",
        "centroid": (40.6129, -73.9947),
        "scores": {"safety": 4.5, "beauty": 3.0, "quiet": 4.0, "residential": 4.5},
        "composite": 4.03,
        "one_liner": "Safe, very residential; modestly built streetscape; strong Italian and Chinese communities.",
        "source": {"base": "Bensonhurst"},
    },
    {
        "rank": 26, "name": "Borough Park", "tier": 3,
        "borough": "Brooklyn",
        "centroid": (40.6305, -73.9904),
        "scores": {"safety": 5.0, "beauty": 3.0, "quiet": 4.5, "residential": 5.0},
        "composite": 4.42,
        "one_liner": "One of Brooklyn's safest and most residential neighborhoods; Orthodox Jewish community; limited nightlife.",
        "source": {"base": "Borough Park"},
    },
    {
        "rank": 27, "name": "Brighton Beach", "tier": 3,
        "borough": "Brooklyn",
        "centroid": (40.5783, -73.9682),
        "scores": {"safety": 4.0, "beauty": 3.0, "quiet": 3.5, "residential": 4.0},
        "composite": 3.64,
        "one_liner": "Vibrant Russian-speaking beachfront community; lively commercial strip; architecturally modest.",
        "source": {"base": "Brighton Beach"},
    },
    {
        "rank": 28, "name": "Columbia St Waterfront", "tier": 3,
        "borough": "Brooklyn",
        "centroid": (40.6860, -74.0049),
        "scores": {"safety": 4.0, "beauty": 3.5, "quiet": 4.0, "residential": 3.5},
        "composite": 3.78,
        "one_liner": "Small transitional waterfront district between Carroll Gardens and Red Hook.",
        "source": {"base": "Columbia St"},
    },
    {
        "rank": 29, "name": "Fort Hamilton", "tier": 3,
        "borough": "Brooklyn",
        "centroid": (40.6150, -74.0312),
        "scores": {"safety": 4.5, "beauty": 3.0, "quiet": 4.5, "residential": 3.5},
        "composite": 3.94,
        "one_liner": "Military base tip of Brooklyn; safe, quiet, mixed residential.",
        "source": {"base": "Fort Hamilton"},
    },
    {
        "rank": 30, "name": "Gerritsen Beach", "tier": 3,
        "borough": "Brooklyn",
        "centroid": (40.5929, -73.9275),
        "scores": {"safety": 4.5, "beauty": 3.0, "quiet": 5.0, "residential": 5.0},
        "composite": 4.41,
        "one_liner": "Extremely quiet and insular working-class waterfront community; no subway; very isolated.",
        "source": {"base": "Gerritsen Beach"},
    },
    {
        "rank": 31, "name": "Gravesend", "tier": 3,
        "borough": "Brooklyn",
        "centroid": (40.5947, -73.9816),
        "scores": {"safety": 4.5, "beauty": 3.0, "quiet": 4.0, "residential": 4.5},
        "composite": 4.03,
        "one_liner": "Safe, residential south Brooklyn; diverse community; modest architecture.",
        "source": {"base": "Gravesend"},
    },
    {
        "rank": 32, "name": "Kensington", "tier": 3,
        "borough": "Brooklyn",
        "centroid": (40.6395, -73.9756),
        "scores": {"safety": 4.0, "beauty": 3.0, "quiet": 4.0, "residential": 4.5},
        "composite": 3.89,
        "one_liner": "Quiet, affordable, diverse residential neighborhood between Park Slope and Windsor Terrace.",
        "source": {"base": "Kensington"},
    },
    {
        "rank": 33, "name": "Marine Park", "tier": 3,
        "borough": "Brooklyn",
        "centroid": (40.6046, -73.9271),
        "scores": {"safety": 4.5, "beauty": 3.0, "quiet": 4.5, "residential": 4.5},
        "composite": 4.17,
        "one_liner": "Very safe, quiet residential neighborhood adjacent to NYC's largest park; no subway.",
        "source": {"base": "Marine Park"},
    },
    {
        "rank": 34, "name": "Midwood", "tier": 3,
        "borough": "Brooklyn",
        "centroid": (40.6201, -73.9606),
        "scores": {"safety": 4.5, "beauty": 3.0, "quiet": 4.0, "residential": 4.5},
        "composite": 4.03,
        "one_liner": "Safe, residential central Brooklyn; Orthodox and Sephardic Jewish community; modest streets.",
        "source": {"base": "Midwood"},
    },
    {
        "rank": 35, "name": "Mill Basin", "tier": 3,
        "borough": "Brooklyn",
        "centroid": (40.6111, -73.9122),
        "scores": {"safety": 4.5, "beauty": 3.0, "quiet": 4.5, "residential": 4.5},
        "composite": 4.17,
        "one_liner": "Safe, quiet waterfront community; detached homes on canals; no subway.",
        "source": {"base": "Mill Basin"},
    },
    {
        "rank": 36, "name": "Sea Gate", "tier": 3,
        "borough": "Brooklyn",
        "centroid": (40.5772, -74.0074),
        "scores": {"safety": 4.5, "beauty": 3.0, "quiet": 5.0, "residential": 4.0},
        "composite": 4.19,
        "one_liner": "Private gated community at Coney Island tip; extremely quiet; isolated.",
        "source": {"base": "Sea Gate"},
    },
    {
        "rank": 37, "name": "Sheepshead Bay", "tier": 3,
        "borough": "Brooklyn",
        "centroid": (40.5960, -73.9496),
        "scores": {"safety": 4.0, "beauty": 3.0, "quiet": 3.5, "residential": 3.5},
        "composite": 3.53,
        "one_liner": "Waterfront fishing community; mixed residential; good transit; architecturally plain.",
        "source": {"base": "Sheepshead Bay"},
    },

    # ── Tier 4 ──────────────────────────────────────────────────────────────
    {
        "rank": 38, "name": "Bedford-Stuyvesant", "tier": 4,
        "borough": "Brooklyn",
        "centroid": (40.6871, -73.9382),
        "scores": {"safety": 3.0, "beauty": 4.0, "quiet": 3.5, "residential": 3.5},
        "composite": 3.47,
        "one_liner": "Iconic brownstones; rapidly gentrifying; safety still variable block by block.",
        "source": {"base": "Bedford-Stuyvesant"},
    },
    {
        "rank": 39, "name": "Bergen Beach", "tier": 4,
        "borough": "Brooklyn",
        "centroid": (40.6194, -73.9050),
        "scores": {"safety": 4.0, "beauty": 2.5, "quiet": 4.5, "residential": 4.5},
        "composite": 3.91,
        "one_liner": "Quiet, safe, isolated residential peninsula; beauty score limits tier.",
        "source": {"base": "Bergen Beach"},
    },
    {
        "rank": 40, "name": "Canarsie", "tier": 4,
        "borough": "Brooklyn",
        "centroid": (40.6388, -73.8997),
        "scores": {"safety": 3.5, "beauty": 2.5, "quiet": 3.5, "residential": 4.0},
        "composite": 3.39,
        "one_liner": "Working-class far-southeast Brooklyn; limited transit; modest architecture.",
        "source": {"base": "Canarsie"},
    },
    {
        "rank": 41, "name": "Coney Island", "tier": 4,
        "borough": "Brooklyn",
        "centroid": (40.5757, -73.9925),
        "scores": {"safety": 3.5, "beauty": 3.0, "quiet": 3.0, "residential": 2.5},
        "composite": 3.03,
        "one_liner": "Historic amusement district; tourist-heavy; limited year-round residential character.",
        "source": {"base": "Coney Island"},
    },
    {
        "rank": 42, "name": "Cypress Hills", "tier": 4,
        "borough": "Brooklyn",
        "centroid": (40.6815, -73.8818),
        "scores": {"safety": 3.0, "beauty": 2.5, "quiet": 3.5, "residential": 3.5},
        "composite": 3.13,
        "one_liner": "Eastern Brooklyn; mixed residential; limited amenities; modest architecture.",
        "source": {"base": "Cypress Hills"},
    },
    {
        "rank": 43, "name": "Downtown Brooklyn", "tier": 4,
        "borough": "Brooklyn",
        "centroid": (40.6948, -73.9865),
        "scores": {"safety": 4.0, "beauty": 3.0, "quiet": 3.0, "residential": 2.5},
        "composite": 3.18,
        "one_liner": "Major transit hub and commercial center; residential feel is limited; improving but office-heavy.",
        "source": {"base": "Downtown Brooklyn"},
    },
    {
        "rank": 44, "name": "East Flatbush", "tier": 4,
        "borough": "Brooklyn",
        "centroid": (40.6477, -73.9329),
        "scores": {"safety": 3.0, "beauty": 2.5, "quiet": 3.5, "residential": 3.5},
        "composite": 3.13,
        "one_liner": "Diverse central Brooklyn; safety and architecture below threshold for this profile.",
        "source": {"base": "East Flatbush"},
    },
    {
        "rank": 45, "name": "Flatlands", "tier": 4,
        "borough": "Brooklyn",
        "centroid": (40.6243, -73.9309),
        "scores": {"safety": 4.0, "beauty": 2.5, "quiet": 4.0, "residential": 4.5},
        "composite": 3.78,
        "one_liner": "Safe, quiet far-south Brooklyn; suburban character; architecture lacks distinction.",
        "source": {"base": "Flatlands"},
    },
    {
        "rank": 46, "name": "Gowanus", "tier": 4,
        "borough": "Brooklyn",
        "centroid": (40.6758, -73.9901),
        "scores": {"safety": 3.5, "beauty": 3.0, "quiet": 3.5, "residential": 3.0},
        "composite": 3.28,
        "one_liner": "Industrial canal corridor; rapidly transitioning; mixed character.",
        "source": {"base": "Gowanus"},
    },
    {
        "rank": 47, "name": "Prospect-Lefferts Gardens", "tier": 4,
        "borough": "Brooklyn",
        "centroid": (40.6596, -73.9513),
        "scores": {"safety": 3.0, "beauty": 3.5, "quiet": 3.5, "residential": 4.0},
        "composite": 3.47,
        "one_liner": "Beautiful brownstones along Lefferts Ave; safety and composite below T3 threshold.",
        "source": {"base": "Prospect-Lefferts Gardens"},
    },
    {
        "rank": 48, "name": "Sunset Park", "tier": 4,
        "borough": "Brooklyn",
        "centroid": (40.6503, -74.0100),
        "scores": {"safety": 3.0, "beauty": 3.0, "quiet": 3.5, "residential": 3.5},
        "composite": 3.24,
        "one_liner": "Diverse, improving; waterfront park has views; safety and composite below threshold.",
        "source": {"base": "Sunset Park"},
    },

    # ── Tier 5 ──────────────────────────────────────────────────────────────
    {
        "rank": 49, "name": "Brownsville", "tier": 5,
        "borough": "Brooklyn",
        "centroid": (40.6638, -73.9103),
        "scores": {"safety": 2.0, "beauty": 2.0, "quiet": 3.0, "residential": 3.5},
        "composite": 2.49,
        "one_liner": "Fails minimum safety threshold; excluded from consideration.",
        "source": {"base": "Brownsville"},
    },
]

# Open space / non-residential areas in Brooklyn (rendered in park color)
BROOKLYN_PARKS = [
    "Prospect Park",
    "Green-Wood Cemetery",
    "Floyd Bennett Field",
    "Jamaica Bay",
    "Plum Beach",
    "Navy Yard",
]
